### ISSUE TITLE
SDL2 OpenGL ES examples do not work on Linux x86-64

### ISSUE THREAD

**Issue by clix9** [mosra/magnum-examples#9]
My prefix folder is /opt and I build everything with BUILD_STATIC=OFF, but I still receive the error

**Utility::Resource: group 'MagnumShaders' was not found**

Whenever I try to run the Triangle example.

Also, the OpenGEX importer does not work with GCC 4.8.2 and the compiler throws errors.

**Comment by mosra** [comment]
Hi,

thanks for the reports!

This particular error is, in fact, really related to static build. Are you sure you didn't link to static `MagnumShaders` library by accident? (For example because CMake found it sooner than the shared one -- look for `MAGNUM_SHADERS_LIBRARY` in `CMakeCache.txt`.) The original point with the example was to keep it as short as possible, but, yeah, that doesn't work with static build. The fix for static build is simple, just adding [these three lines](https://github.com/mosra/magnum-examples/blob/3bd5f46af042691c76cf1bc8cde5c2c656764606/src/triangle/TriangleExample.cpp#L39-L41). I'll add these or find a way to avoid these inconveniences altogether.

Incidentally, I tested the OpenGEX importer on GCC 4.9 and 4.7 and it worked on both, so I expected it to work also on all versions in between. Guess I need to install 4.8 and test it also there, then :)

**Comment by clix9** [comment]
Thanks. The demos compiled and worked when I deleted the caches and rebuilt all the projects, including the demos, with the STATIC_BUILD=OFF option. But I had to explicitly mention the libEGL library in the examples' CMake files because of undefined references to a specific EGL method.

Here is the type of errors I receive when building the OpenGEXImporter with 64-bit GCC 4.8.2 on Linux. 

**....../MagnumPlugins/OpenGexImporter/OpenDdl/parsers.cpp:328:52: error: redeclaration ‘Magnum::OpenDdl::Type Magnum::OpenDdl::Implementation::{anonymous}::typeFor() [with <template-parameter-1-1> = unsigned char]’ differs in ‘constexpr’
 #define _c(T) template<> constexpr Type typeFor<T>() { return Type::T; }**

I instead used Clang++ 3.4 to build the plug-ins.

**Comment by mosra** [comment]
Okay, so:

- examples with static builds should be [working](https://github.com/mosra/magnum/commit/9d326d4ff136bfc5c26ace4739a9a2444638c6c2) now, no more `group 'MagnumShaders' was not found` messages
- EGL linking is now also [done automatically](https://github.com/mosra/magnum/commit/eebb5d4af59e7834bd1e12f8302d0d99aabdc9d2)
- OpenGEX plugin (and everything else) [now builds](https://github.com/mosra/magnum-plugins/commit/46942c488ae6153e612a1ac7df50b890ce737203) also on GCC 4.8 without errors and test failures

Note that you need to pull new changes also from Corrade to make the fixes compilable.

Thanks for all the reports!
